/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MapRouteImport } from './routes/map'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DropsRouteImport } from './routes/drops'
import { Route as CirclesRouteImport } from './routes/circles'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as DropsIndexRouteImport } from './routes/drops.index'
import { Route as CirclesIndexRouteImport } from './routes/circles.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as MarketplaceSlugRouteImport } from './routes/marketplace.$slug'
import { Route as DropsSlugRouteImport } from './routes/drops.$slug'
import { Route as CirclesSlugRouteImport } from './routes/circles.$slug'
import { Route as ApiConciergeRouteImport } from './routes/api/concierge'
import { Route as AuthenticatedProviderRouteImport } from './routes/_authenticated/provider'
import { Route as AuthenticatedNetworkRouteImport } from './routes/_authenticated/network'
import { Route as AuthenticatedEmployerRouteImport } from './routes/_authenticated/employer'
import { Route as AuthenticatedEmployeeRouteImport } from './routes/_authenticated/employee'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings.profile'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DropsRoute = DropsRouteImport.update({
  id: '/drops',
  path: '/drops',
  getParentRoute: () => rootRouteImport,
} as any)
const CirclesRoute = CirclesRouteImport.update({
  id: '/circles',
  path: '/circles',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const DropsIndexRoute = DropsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DropsRoute,
} as any)
const CirclesIndexRoute = CirclesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CirclesRoute,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceSlugRoute = MarketplaceSlugRouteImport.update({
  id: '/marketplace/$slug',
  path: '/marketplace/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DropsSlugRoute = DropsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DropsRoute,
} as any)
const CirclesSlugRoute = CirclesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CirclesRoute,
} as any)
const ApiConciergeRoute = ApiConciergeRouteImport.update({
  id: '/api/concierge',
  path: '/api/concierge',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProviderRoute = AuthenticatedProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNetworkRoute = AuthenticatedNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployerRoute = AuthenticatedEmployerRouteImport.update({
  id: '/employer',
  path: '/employer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployeeRoute = AuthenticatedEmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/circles': typeof CirclesRouteWithChildren
  '/drops': typeof DropsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/map': typeof MapRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/employee': typeof AuthenticatedEmployeeRoute
  '/employer': typeof AuthenticatedEmployerRoute
  '/network': typeof AuthenticatedNetworkRoute
  '/provider': typeof AuthenticatedProviderRoute
  '/api/concierge': typeof ApiConciergeRoute
  '/circles/$slug': typeof CirclesSlugRoute
  '/drops/$slug': typeof DropsSlugRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/circles/': typeof CirclesIndexRoute
  '/drops/': typeof DropsIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/map': typeof MapRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/employee': typeof AuthenticatedEmployeeRoute
  '/employer': typeof AuthenticatedEmployerRoute
  '/network': typeof AuthenticatedNetworkRoute
  '/provider': typeof AuthenticatedProviderRoute
  '/api/concierge': typeof ApiConciergeRoute
  '/circles/$slug': typeof CirclesSlugRoute
  '/drops/$slug': typeof DropsSlugRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/circles': typeof CirclesIndexRoute
  '/drops': typeof DropsIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/circles': typeof CirclesRouteWithChildren
  '/drops': typeof DropsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/map': typeof MapRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/employee': typeof AuthenticatedEmployeeRoute
  '/_authenticated/employer': typeof AuthenticatedEmployerRoute
  '/_authenticated/network': typeof AuthenticatedNetworkRoute
  '/_authenticated/provider': typeof AuthenticatedProviderRoute
  '/api/concierge': typeof ApiConciergeRoute
  '/circles/$slug': typeof CirclesSlugRoute
  '/drops/$slug': typeof DropsSlugRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/circles/': typeof CirclesIndexRoute
  '/drops/': typeof DropsIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/circles'
    | '/drops'
    | '/forgot-password'
    | '/map'
    | '/reset-password'
    | '/admin'
    | '/employee'
    | '/employer'
    | '/network'
    | '/provider'
    | '/api/concierge'
    | '/circles/$slug'
    | '/drops/$slug'
    | '/marketplace/$slug'
    | '/u/$username'
    | '/circles/'
    | '/drops/'
    | '/marketplace/'
    | '/settings/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/map'
    | '/reset-password'
    | '/admin'
    | '/employee'
    | '/employer'
    | '/network'
    | '/provider'
    | '/api/concierge'
    | '/circles/$slug'
    | '/drops/$slug'
    | '/marketplace/$slug'
    | '/u/$username'
    | '/circles'
    | '/drops'
    | '/marketplace'
    | '/settings/profile'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/circles'
    | '/drops'
    | '/forgot-password'
    | '/map'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/employee'
    | '/_authenticated/employer'
    | '/_authenticated/network'
    | '/_authenticated/provider'
    | '/api/concierge'
    | '/circles/$slug'
    | '/drops/$slug'
    | '/marketplace/$slug'
    | '/u/$username'
    | '/circles/'
    | '/drops/'
    | '/marketplace/'
    | '/_authenticated/settings/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CirclesRoute: typeof CirclesRouteWithChildren
  DropsRoute: typeof DropsRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  MapRoute: typeof MapRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiConciergeRoute: typeof ApiConciergeRoute
  MarketplaceSlugRoute: typeof MarketplaceSlugRoute
  UUsernameRoute: typeof UUsernameRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drops': {
      id: '/drops'
      path: '/drops'
      fullPath: '/drops'
      preLoaderRoute: typeof DropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circles': {
      id: '/circles'
      path: '/circles'
      fullPath: '/circles'
      preLoaderRoute: typeof CirclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drops/': {
      id: '/drops/'
      path: '/'
      fullPath: '/drops/'
      preLoaderRoute: typeof DropsIndexRouteImport
      parentRoute: typeof DropsRoute
    }
    '/circles/': {
      id: '/circles/'
      path: '/'
      fullPath: '/circles/'
      preLoaderRoute: typeof CirclesIndexRouteImport
      parentRoute: typeof CirclesRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$slug': {
      id: '/marketplace/$slug'
      path: '/marketplace/$slug'
      fullPath: '/marketplace/$slug'
      preLoaderRoute: typeof MarketplaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drops/$slug': {
      id: '/drops/$slug'
      path: '/$slug'
      fullPath: '/drops/$slug'
      preLoaderRoute: typeof DropsSlugRouteImport
      parentRoute: typeof DropsRoute
    }
    '/circles/$slug': {
      id: '/circles/$slug'
      path: '/$slug'
      fullPath: '/circles/$slug'
      preLoaderRoute: typeof CirclesSlugRouteImport
      parentRoute: typeof CirclesRoute
    }
    '/api/concierge': {
      id: '/api/concierge'
      path: '/api/concierge'
      fullPath: '/api/concierge'
      preLoaderRoute: typeof ApiConciergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/provider': {
      id: '/_authenticated/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof AuthenticatedProviderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/network': {
      id: '/_authenticated/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AuthenticatedNetworkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer': {
      id: '/_authenticated/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof AuthenticatedEmployerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employee': {
      id: '/_authenticated/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof AuthenticatedEmployeeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedEmployeeRoute: typeof AuthenticatedEmployeeRoute
  AuthenticatedEmployerRoute: typeof AuthenticatedEmployerRoute
  AuthenticatedNetworkRoute: typeof AuthenticatedNetworkRoute
  AuthenticatedProviderRoute: typeof AuthenticatedProviderRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedEmployeeRoute: AuthenticatedEmployeeRoute,
  AuthenticatedEmployerRoute: AuthenticatedEmployerRoute,
  AuthenticatedNetworkRoute: AuthenticatedNetworkRoute,
  AuthenticatedProviderRoute: AuthenticatedProviderRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CirclesRouteChildren {
  CirclesSlugRoute: typeof CirclesSlugRoute
  CirclesIndexRoute: typeof CirclesIndexRoute
}

const CirclesRouteChildren: CirclesRouteChildren = {
  CirclesSlugRoute: CirclesSlugRoute,
  CirclesIndexRoute: CirclesIndexRoute,
}

const CirclesRouteWithChildren =
  CirclesRoute._addFileChildren(CirclesRouteChildren)

interface DropsRouteChildren {
  DropsSlugRoute: typeof DropsSlugRoute
  DropsIndexRoute: typeof DropsIndexRoute
}

const DropsRouteChildren: DropsRouteChildren = {
  DropsSlugRoute: DropsSlugRoute,
  DropsIndexRoute: DropsIndexRoute,
}

const DropsRouteWithChildren = DropsRoute._addFileChildren(DropsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CirclesRoute: CirclesRouteWithChildren,
  DropsRoute: DropsRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  MapRoute: MapRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiConciergeRoute: ApiConciergeRoute,
  MarketplaceSlugRoute: MarketplaceSlugRoute,
  UUsernameRoute: UUsernameRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
