/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProviderRouteImport } from './routes/_authenticated/provider'
import { Route as AuthenticatedEmployerRouteImport } from './routes/_authenticated/employer'
import { Route as AuthenticatedEmployeeRouteImport } from './routes/_authenticated/employee'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProviderRoute = AuthenticatedProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployerRoute = AuthenticatedEmployerRouteImport.update({
  id: '/employer',
  path: '/employer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployeeRoute = AuthenticatedEmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/employee': typeof AuthenticatedEmployeeRoute
  '/employer': typeof AuthenticatedEmployerRoute
  '/provider': typeof AuthenticatedProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/employee': typeof AuthenticatedEmployeeRoute
  '/employer': typeof AuthenticatedEmployerRoute
  '/provider': typeof AuthenticatedProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/employee': typeof AuthenticatedEmployeeRoute
  '/_authenticated/employer': typeof AuthenticatedEmployerRoute
  '/_authenticated/provider': typeof AuthenticatedProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/employee'
    | '/employer'
    | '/provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/employee'
    | '/employer'
    | '/provider'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/employee'
    | '/_authenticated/employer'
    | '/_authenticated/provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/provider': {
      id: '/_authenticated/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof AuthenticatedProviderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer': {
      id: '/_authenticated/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof AuthenticatedEmployerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employee': {
      id: '/_authenticated/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof AuthenticatedEmployeeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEmployeeRoute: typeof AuthenticatedEmployeeRoute
  AuthenticatedEmployerRoute: typeof AuthenticatedEmployerRoute
  AuthenticatedProviderRoute: typeof AuthenticatedProviderRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEmployeeRoute: AuthenticatedEmployeeRoute,
  AuthenticatedEmployerRoute: AuthenticatedEmployerRoute,
  AuthenticatedProviderRoute: AuthenticatedProviderRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
